import sqlite3

db_path = r"C:\Users\24948\AppData\Local\Firaxis Games\Sid Meier's Civilization VI\Cache\DebugGameplay.sqlite"
conn = sqlite3.connect(db_path)
cur = conn.cursor()

# List of 92 diplomacy EffectTypes
effects = [
    "EFFECT_ADD_DIPLOMATIC_ACTION_OVERRIDE",
    "EFFECT_ADD_DIPLOMATIC_COMBAT_MODIFIER",
    "EFFECT_ADD_DIPLOMATIC_MOVEMENT_MODIFIER",
    "EFFECT_ADD_DIPLOMATIC_YIELD_MODIFIER",
    "EFFECT_ADD_PLAYER_FAVOR",
    "EFFECT_ADJUST_BANNED_DIPLOMATIC_ACTIONS",
    "EFFECT_ADJUST_BANNED_DIPLOMATIC_ACTIONS_SPECIFIC_CIVILIZATION",
    "EFFECT_ADJUST_DIPLOMATIC_ACTION_PREFERENCE",
    "EFFECT_ADJUST_DISABLE_INFLUENCE",
    "EFFECT_ADJUST_DUPLICATE_FIRST_INFLUENCE_TOKEN",
    "EFFECT_ADJUST_DUPLICATE_INFLUENCE_TOKEN_WHEN_RIVAL_GOVERNMENT",
    "EFFECT_ADJUST_DUPLICATE_INFLUENCE_TOKEN_WHEN_SAME_RELIGION",
    "EFFECT_ADJUST_INFLUENCE_POINTS_PER_TURN",
    "EFFECT_ADJUST_PLAYER_ADJUST_ENVOYS_NON_SPECIALTY",
    "EFFECT_ADJUST_PLAYER_ANYONE_PLUNDER_FAVOR",
    "EFFECT_ADJUST_PLAYER_DIPLOMATIC_VICTORY_POINTS",
    "EFFECT_ADJUST_PLAYER_EMERGENCY_FAVOR_MODIFIER",
    "EFFECT_ADJUST_PLAYER_EXTRA_FAVOR_PER_TURN",
    "EFFECT_ADJUST_PLAYER_FAVOR_REFUND_FOR_SUCCESSFUL_RESOLUTION",
    "EFFECT_ADJUST_PLAYER_GOVERNMENT_SLOT_TYPE_GRANT_FAVOR",
    "EFFECT_ADJUST_PLAYER_GOVERNOR_FAVOR",
    "EFFECT_ADJUST_PLAYER_GREATPERSON_FAVOR_MODIFIER",
    "EFFECT_ADJUST_PLAYER_GRIEVANCE_DECAY",
    "EFFECT_ADJUST_PLAYER_GRIEVANCE_GENERATION",
    "EFFECT_ADJUST_PLAYER_OPEN_BORDERS_FROM_INFLUENCE",
    "EFFECT_ADJUST_PLAYER_POLICY_FAVOR",
    "EFFECT_ADJUST_PLAYER_SEND_INFLUENCE_TOKEN_FAVOR_BY_BONUS_TYPE",
    "EFFECT_ADJUST_PLAYER_SUZERAIN_FAVOR_BY_BONUS_TYPE",
    "EFFECT_ADJUST_PLAYER_SUZERAIN_FAVOR_MULTIPLIER",
    "EFFECT_ADJUST_PLAYER_TOURISM_FAVOR",
    "EFFECT_ADJUST_PLAYER_YIELD_CHANGE_PER_USED_INFLUENCE_TOKEN",
    "EFFECT_ADJUST_RELIGION_ANYONE_CONDEMNS_FAVOR",
    "EFFECT_DIPLOMACY_AGENDA_ANGEVIN_EMPIRE",
    "EFFECT_DIPLOMACY_AGENDA_ARCHIPELAGIC_STATE",
    "EFFECT_DIPLOMACY_AGENDA_AYYUBID_DYNASTY",
    "EFFECT_DIPLOMACY_AGENDA_BLACK_QUEEN",
    "EFFECT_DIPLOMACY_AGENDA_BULL_MOOSE",
    "EFFECT_DIPLOMACY_AGENDA_BUSHIDO",
    "EFFECT_DIPLOMACY_AGENDA_CANADIAN_EXPEDITIONARY",
    "EFFECT_DIPLOMACY_AGENDA_END_TO_SUFFERING",
    "EFFECT_DIPLOMACY_AGENDA_ENVIRONMENT",
    "EFFECT_DIPLOMACY_AGENDA_ETHIOPIAN_HIGHLANDS",
    "EFFECT_DIPLOMACY_AGENDA_EXPLOITATIVE",
    "EFFECT_DIPLOMACY_AGENDA_FLAT_EARTHER",
    "EFFECT_DIPLOMACY_AGENDA_HORN_CHEST_LOINS",
    "EFFECT_DIPLOMACY_AGENDA_HORSE_LORD",
    "EFFECT_DIPLOMACY_AGENDA_KAITIAKITANGA",
    "EFFECT_DIPLOMACY_AGENDA_KUBLAI_PAX",
    "EFFECT_DIPLOMACY_AGENDA_LAST_VIKING_KING",
    "EFFECT_DIPLOMACY_AGENDA_LAWGIVER",
    "EFFECT_DIPLOMACY_AGENDA_LORD_OF_MINES",
    "EFFECT_DIPLOMACY_AGENDA_MAGNIFICENCES",
    "EFFECT_DIPLOMACY_AGENDA_OPPORTUNIST",
    "EFFECT_DIPLOMACY_AGENDA_OPTIMUS_PRINCEPS",
    "EFFECT_DIPLOMACY_AGENDA_PARANOID",
    "EFFECT_DIPLOMACY_AGENDA_PATRON_OF_ARTS",
    "EFFECT_DIPLOMACY_AGENDA_PERPETUALLY_ON_GUARD",
    "EFFECT_DIPLOMACY_AGENDA_QUEEN_OF_NILE",
    "EFFECT_DIPLOMACY_AGENDA_RAVEN_BANNER",
    "EFFECT_DIPLOMACY_AGENDA_SHORT_LIFE_GLORY",
    "EFFECT_DIPLOMACY_AGENDA_SIMON_BOLIVAR",
    "EFFECT_DIPLOMACY_AGENDA_TRIEU_DEFENDER",
    "EFFECT_DIPLOMACY_AGENDA_TURTLER",
    "EFFECT_DIPLOMACY_AGENDA_WITH_SHIELD_OR_ON_IT",
    "EFFECT_DIPLOMACY_AGENDA_ZEALOT",
    "EFFECT_DIPLOMACY_ARCHAEOLOGY",
    "EFFECT_DIPLOMACY_BROKEN_PLEDGE",
    "EFFECT_DIPLOMACY_BROKEN_PROMISE",
    "EFFECT_DIPLOMACY_CULTURAL_ID",
    "EFFECT_DIPLOMACY_ESPIONAGE",
    "EFFECT_DIPLOMACY_FORCE_INCURSION",
    "EFFECT_DIPLOMACY_GOVERNMENTS",
    "EFFECT_DIPLOMACY_KEPT_PLEDGE",
    "EFFECT_DIPLOMACY_KEPT_PROMISE",
    "EFFECT_DIPLOMACY_NEW_WARMONGER",
    "EFFECT_DIPLOMACY_NO_PLEDGE",
    "EFFECT_DIPLOMACY_NO_PROMISE",
    "EFFECT_DIPLOMACY_RANDOM",
    "EFFECT_DIPLOMACY_SETTLED_CITIES",
    "EFFECT_DIPLOMACY_SIMPLE_EFFECT",
    "EFFECT_DIPLOMACY_THIRD_PARTY_EFFECTS",
    "EFFECT_DIPLOMACY_THIRD_PARTY_WARMONGER",
    "EFFECT_DISABLE_PLAYER_GRIEVANCE_DECAY",
    "EFFECT_ENABLE_RELIGION_AWARDS_ENVOY",
    "EFFECT_ENABLE_RELIGION_AWARDS_ENVOY_RELIGIOUS_PRESSURE",
    "EFFECT_GRANT_CITY_OWNER_INFLUENCE_TOKEN_WONDER",
    "EFFECT_GRANT_FREE_ENVOYS_HERE",
    "EFFECT_GRANT_INFLUENCE_TOKEN",
    "EFFECT_GRANT_INFLUENCE_TOKEN_LEVY_MILITARY",
    "EFFECT_PLAYER_ADJUST_FAVOR_FROM_DELEGATIONS",
    "EFFECT_PLAYER_ADJUST_FAVOR_FROM_EMBASSIES",
    "EFFECT_PLAYER_DIPLOMACY_AGENDA_COMPARE_ARMY_SIZE",
]

print("EffectType|ModifierType|CollectionType|Arguments")
print("=" * 120)

for effect in effects:
    # Find ModifierIds tagged with this EffectType
    cur.execute("""
        SELECT DISTINCT dm.ModifierType, dm.CollectionType, m.ModifierId
        FROM Types t
        JOIN TypeTags tt ON t.Type = tt.Type
        JOIN Modifiers m ON tt.Tag = m.ModifierId
        JOIN DynamicModifiers dm ON m.ModifierType = dm.ModifierType
        WHERE t.Type = ? AND tt.Tag LIKE 'EFFECT_%'
    """, (effect,))

    dm_rows = cur.fetchall()

    if not dm_rows:
        # Try alternative: maybe the tag IS the EffectType directly?
        cur.execute("""
            SELECT DISTINCT dm.ModifierType, dm.CollectionType, m.ModifierId
            FROM Modifiers m
            JOIN DynamicModifiers dm ON m.ModifierType = dm.ModifierType
            WHERE m.ModifierType LIKE ?
        """, (effect.replace('EFFECT_', '%') + '%',))
        dm_rows = cur.fetchall()

    if not dm_rows:
        print(f"{effect}|NOT FOUND||")
        continue

    # Collect unique (ModifierType, CollectionType) pairs
    mt_ct_set = set()
    args_info = {}
    sample_modifier_id = None

    for mt, ct, mid in dm_rows:
        mt_ct_set.add((mt, ct))
        if sample_modifier_id is None:
            sample_modifier_id = mid

    # Get ModifierArguments for a sample ModifierId
    if sample_modifier_id:
        cur.execute("""
            SELECT ma.Name, ma.Value, ma.Type
            FROM ModifierArguments ma
            WHERE ma.ModifierId = ?
            ORDER BY ma.Name
        """, (sample_modifier_id,))
        args_rows = cur.fetchall()
    else:
        args_rows = []

    # Output
    for mt, ct in sorted(mt_ct_set):
        args_str = "; ".join(f"{name}={val}" for name, val, typ in args_rows)
        print(f"{effect}|{mt}|{ct}|{args_str}")

conn.close()
